name: 豆瓣爬虫ubuntu版

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v1

      - name: 'Setup Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: 'Install requirements'
        run: |
          python -m pip install --upgrade pip && \
          pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple

      -name: 'Build'
        run: |
          pyinstaller -F test.py